version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: laravel_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  volumes:
    pgdata:
    